eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.instance-id=${spring.cloud.client.hostname}:${spring.application.name}:${server.port}
server.port=${PORT:0}
eureka.instance.prefer-ip-address=true
