server.port=8081
spring.datasource.url= jdbc:mysql://localhost:3306/customerdb
friendFamilyRibbon.ribbon.eureka.enabled=false
friendFamilyRibbon.ribbon.listOfServers=http://localhost:8083,http://localhost:8089
