server.port=${PORT:0}
eureka.client.service-url.defaultZone=http://localhost:2222/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.instance-id=${spring.cloud.client.hostname}:${spring.application.name}:${random.value}
